[package]
name = "agg-wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
agg-rust = { path = "../..", features = ["font"] }
js-sys = "0.3.85"
wasm-bindgen = "0.2"
